import type { NextPage } from 'next'
import Head from 'next/head'


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores accusantium nemo velit, eum voluptates optio doloremque cumque ullam minima sed sunt quod totam dolor atque doloribus hic, ratione unde ad!</p>
      </main>
</>
  )
}

export default Home
